[package]
name = "genesis_updater"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "genesis_updater"
path = "src/main.rs"

[dependencies]
indy = "1.16.0"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
log = "0.4.16"
unescape = "0.1.0"
